#!/bin/bash

# Set the path to the crackme2 executable
crackme_path="path/to/crackme2"

# Use ltrace to trace library calls and find the password
password=$(ltrace -s 1000 -e getenv,strcmp -i $crackme_path 2>&1 | grep "PASSWORD=" | cut -d '=' -f 2)

# Output the password to a file
echo -n $password > crackme2_password.txt

echo "Password extracted and saved to crackme2_password.tx"

